import Head from "next/head";
import { useWeb3 } from "@3rdweb/hooks";
import Dashboard from "./Dashboard";

export default function Home({ sanityTokens }) {
  const { address, connectWallet } = useWeb3();

  return (
    <div className="max-h-screen max-w-screen overflow-hidden">
      <Head>
        <title>ZH Coinbase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen max-w-screen gradient-bg text-white">
        {address ? (
          <Dashboard address={address} sanityTokens={sanityTokens} />
        ) : (
          <div className="w-screen h-screen flex items-center justify-center">
            <div className="flex flex-col items-center justify-center ">
              <h1 className="text-lg xl:text-5xl my-10">
                Welcome to ZH Coinbase
              </h1>
              <button
                onClick={() => connectWallet("injected")}
                className="text-gray-400 border border-[#282b2f] px-10 py-3 loginbutton hover:loginbutton:hover  font-medium rounded-xl hover:text-white"
              >
                Connect Wallet
              </button>
            </div>
          </div>
        )}
      </main>
    </div>
  );
}
export const getServerSideProps = async () => {
  const coins = await fetch(
    "https://h794aezm.api.sanity.io/v1/data/query/production?query=*%5B_type%3D%3D%20%27coins%27%5D%7B%0A%20%20coins%2CusdPrice%2CcontractAddress%2Csymbol%2Clogo%0A%7D"
  );
  const sanityTokens = (await coins.json()).result;

  return {
    props: {
      sanityTokens,
    },
  };
};
